---
- name: Update sudo to resolve CVE-2017-1000367
  hosts: all
  become: yes
  vars:
    vulnerable_versions:
      - sudo-1.6.8p12-12.el5
      - sudo-1.6.9p17-3.el5
      - sudo-1.6.9p17-3.el5_3.1
      - sudo-1.6.9p17-5.el5
      - sudo-1.6.9p17-6.el5_4
      - sudo-1.7.2p1-5.el5
      - sudo-1.7.2p1-6.el5_5
      - sudo-1.7.2p1-7.el5_5
      - sudo-1.7.2p1-8.el5_5
      - sudo-1.7.2p1-9.el5_5
      - sudo-1.7.2p1-10.el5
      - sudo-1.7.2p1-13.el5
      - sudo-1.7.2p1-14.el5_8
      - sudo-1.7.2p1-14.el5_8.2
      - sudo-1.7.2p1-14.el5_8.3
      - sudo-1.7.2p1-14.el5_8.4
      - sudo-1.7.2p1-22.el5
      - sudo-1.7.2p1-22.el5_9.1
      - sudo-1.7.2p1-28.el5
      - sudo-1.7.2p1-29.el5_10
      - sudo-1.7.4p5-5.el6
      - sudo-1.7.4p5-6.el6_1
      - sudo-1.7.4p5-7.el6
      - sudo-1.7.4p5-9.el6_2
      - sudo-1.7.4p5-11.el6
      - sudo-1.7.4p5-12.el6_3
      - sudo-1.7.4p5-13.el6_3
      - sudo-1.7.4p5-13.el6_3.1
      - sudo-1.8.6p3-7.el6
      - sudo-1.8.6p3-12.el6
      - sudo-1.8.6p3-15.el6
      - sudo-1.8.6p3-19.el6
      - sudo-1.8.6p3-20.el6_7
      - sudo-1.8.6p3-24.el6
      - sudo-1.8.6p3-25.el6_8
      - sudo-1.8.6p3-27.el6
      - sudo-1.8.6p7-11.el7
      - sudo-1.8.6p7-13.el7
      - sudo-1.8.6p7-16.el7
      - sudo-1.8.6p7-17.el7_2
      - sudo-1.8.6p7-20.el7
      - sudo-1.8.6p7-21.el7_3

  tasks:
    - name: Update sudo to latest available
      yum:
        name: sudo
        state: latest

    - name: Get installed version of sudo
      command: rpm -q --qf="%{NAME}-%{VERSION}-%{RELEASE}\n" sudo warn=no
      register: sudo_version
      changed_when: false

    - name: Check installed version of sudo against vulnerable list
      fail:
        msg: Vulnerable version still installed
      when: sudo_version.stdout in vulnerable_versions
